language: cpp
matrix:
  include:
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - lcov
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - lcov
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

script:
  - mkdir -p build/run
  - cd build/run
  - cmake ../.. -DCMAKE_BUILD_TYPE=Coverage
  - make install
  - cd ../..
  - ./bin/bip39_tests

after_success:
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash)
