language: cpp
  
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      group: deprecated-2017Q3
      
      env:
        - MATRIX_EVAL="Name=PlatformIO"
        - INSTALL_SCRIPT="./.travis/install_platform_io.sh"
        - BUILD_SCRIPT="./.travis/script_platform_io.sh"
        
    - os: linux
      dist: trusty
      sudo: required
      group: deprecated-2017Q3
      
      cache:
        directories:
          - ~/arduino_ide
          - ~/.arduino15/packages/
      git:
        depth: false
        quiet: true
      
      env:
        - MATRIX_EVAL="Name=ArduinoIDE"
        - INSTALL_SCRIPT="source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)"
        - BUILD_SCRIPT="./.travis/script_arduino_ide.sh"
  
    - os: linux
      dist: trusty
      sudo: required
      
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - lcov
            
      env:
        - MATRIX_EVAL="Name=GCC7 && CC=gcc-7 && CXX=g++-7"
        - INSTALL_SCRIPT=""
        - BUILD_SCRIPT="./.travis/script_desktop.sh"
        
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - libstdc++-7-dev
            - lcov
      env:
        - MATRIX_EVAL="Name=Clang7 && CC=clang-7 && CXX=clang++-7"
        - INSTALL_SCRIPT=""
        - BUILD_SCRIPT="./.travis/script_desktop.sh"
        
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      addons:
        homebrew:
          packages:
            - lcov
      env:
        - COMPILER=clang++
        - MATRIX_EVAL="Name=MacOS_Clang"
        - INSTALL_SCRIPT=""
        - BUILD_SCRIPT="./.travis/script_desktop.sh"
        
    - os: osx
      osx_image: xcode9.3beta
      addons:
        homebrew:
          packages:
            - lcov
      env:
        - MATRIX_EVAL="Name=MacOS_GCC"
        - INSTALL_SCRIPT=""
        - BUILD_SCRIPT="./.travis/script_desktop.sh"
        
    #
    # Clang Tidy
    #
    - os: linux
      env:
        - MATRIX_EVAL="Name=ClangTidy && CC=clang-7 && CXX=clang++-7"
        - INSTALL_SCRIPT=""
        - BUILD_SCRIPT="./.travis/script_clang_tidy.sh"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - libstdc++-7-dev
            - clang-tidy-7
            
    #
    # Clang Format
    #
    - os: linux
      env:
        - MATRIX_EVAL="Name=ClangFromat && CC=clang-7 && CXX=clang++-7"
        - INSTALL_SCRIPT=""
        - BUILD_SCRIPT="./.travis/script_clang_format.sh"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - libstdc++-7-dev
            - clang-format-7
 
before_install:
    - eval "${MATRIX_EVAL}"
    - chmod -R +x ./.travis/*.sh 
 
install:
  - ${INSTALL_SCRIPT}

script:
  - ${BUILD_SCRIPT}

after_success:
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash)
